# Generated by Django 3.1.2 on 2020-10-30 21:03

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.TextField(blank=True, default='')),
                ('content', picklefield.fields.PickledObjectField(blank=True, default=None, editable=False)),
                ('message_headers', models.TextField()),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='mailviewer_database_backend.emailmessage')),
            ],
            options={
                'db_table': 'mail_viewer_emailmessage',
            },
        ),
    ]
